import './globals.css';
import { body } from './fonts';
import Menu from './common-components/menu';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={body.className}>
                <Menu />
                <div className='content'>{children}</div>
            </body>
        </html>
    );
}
